/* Generated By:JavaCC: Do not edit this line. ParserShipsConstants.java */
package pt.rmartins.battleships.parser.ships;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserShipsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DDOT = 7;
  /** RegularExpression Id. */
  int VERSION = 8;
  /** RegularExpression Id. */
  int LANGUAGES = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int CHAR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"Version\"",
    "\"Languages\"",
    "<NUM>",
    "<ID>",
    "<DIGIT>",
    "<CHAR>",
  };

}
