/* Generated By:JavaCC: Do not edit this line. ParserGameModesConstants.java */
package pt.rmartins.battleships.parser.gamemodes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserGameModesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 5;
  /** RegularExpression Id. */
  int RPAR = 6;
  /** RegularExpression Id. */
  int LSBRA = 7;
  /** RegularExpression Id. */
  int RSBRA = 8;
  /** RegularExpression Id. */
  int LBRA = 9;
  /** RegularExpression Id. */
  int RBRA = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int DDOT = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int MULT = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int MOD = 19;
  /** RegularExpression Id. */
  int VERSION = 20;
  /** RegularExpression Id. */
  int HITS = 21;
  /** RegularExpression Id. */
  int NORMAL_SHOT = 22;
  /** RegularExpression Id. */
  int INDESTRUCTIBLE_SHOT = 23;
  /** RegularExpression Id. */
  int CAMERA_SHOT = 24;
  /** RegularExpression Id. */
  int NOTHING = 25;
  /** RegularExpression Id. */
  int MESSAGES_MODE = 26;
  /** RegularExpression Id. */
  int NORMAL = 27;
  /** RegularExpression Id. */
  int NDELAY = 28;
  /** RegularExpression Id. */
  int TIME_SAVE = 29;
  /** RegularExpression Id. */
  int FULL_SHIELD = 30;
  /** RegularExpression Id. */
  int TIME_LIMIT = 31;
  /** RegularExpression Id. */
  int UNLIMITED = 32;
  /** RegularExpression Id. */
  int BONUS_PLAY = 33;
  /** RegularExpression Id. */
  int EXTRA_TIME = 34;
  /** RegularExpression Id. */
  int EXTRA_TURN = 35;
  /** RegularExpression Id. */
  int FIRST_BLOOD = 36;
  /** RegularExpression Id. */
  int KILL = 37;
  /** RegularExpression Id. */
  int DOUBLE_KILL = 38;
  /** RegularExpression Id. */
  int TRIPLE_KILL = 39;
  /** RegularExpression Id. */
  int ULTRA_KILL = 40;
  /** RegularExpression Id. */
  int RAMPAGE = 41;
  /** RegularExpression Id. */
  int NO_WATER_IN_A_ROW = 42;
  /** RegularExpression Id. */
  int KILLING_SPREE = 43;
  /** RegularExpression Id. */
  int DOMINATING = 44;
  /** RegularExpression Id. */
  int MEGA_KILL = 45;
  /** RegularExpression Id. */
  int UNSTOPPABLE = 46;
  /** RegularExpression Id. */
  int WICKED_SICK = 47;
  /** RegularExpression Id. */
  int MONSTER_KILL = 48;
  /** RegularExpression Id. */
  int GODLIKE = 49;
  /** RegularExpression Id. */
  int HOLY_SHIT = 50;
  /** RegularExpression Id. */
  int SHIPS = 51;
  /** RegularExpression Id. */
  int SHIELD = 52;
  /** RegularExpression Id. */
  int EXPLOSIVE = 53;
  /** RegularExpression Id. */
  int EACH_ALIVE_SHOTS = 54;
  /** RegularExpression Id. */
  int ANY_ALIVE_SHOTS = 55;
  /** RegularExpression Id. */
  int EACH_DEAD_SHOTS = 56;
  /** RegularExpression Id. */
  int ALL_DEAD_SHOTS = 57;
  /** RegularExpression Id. */
  int NUM = 58;
  /** RegularExpression Id. */
  int ID = 59;
  /** RegularExpression Id. */
  int DIGIT = 60;
  /** RegularExpression Id. */
  int CHAR = 61;
  /** RegularExpression Id. */
  int DECIMAL = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"Version\"",
    "\"Hits\"",
    "\"NormalShot\"",
    "\"IndestructibleShot\"",
    "\"CameraShot\"",
    "\"Nothing\"",
    "\"MessagesMode\"",
    "\"Normal\"",
    "\"NDelay\"",
    "\"TimeSave\"",
    "\"FullShield\"",
    "\"TimeLimit\"",
    "\"Unlimited\"",
    "\"BonusPlay\"",
    "\"ExtraTime\"",
    "\"ExtraTurn\"",
    "\"FirstBlood\"",
    "\"Kill\"",
    "\"DoubleKill\"",
    "\"TripleKill\"",
    "\"UltraKill\"",
    "\"Rampage\"",
    "\"NoWaterInARow\"",
    "\"KillingSpree\"",
    "\"Dominating\"",
    "\"MegaKill\"",
    "\"Unstoppable\"",
    "\"WickedSick\"",
    "\"MonsterKill\"",
    "\"Godlike\"",
    "\"HolyShit\"",
    "\"Ships\"",
    "\"Shield\"",
    "\"Explosive\"",
    "\"EachAliveShots\"",
    "\"AnyAliveShots\"",
    "\"EachDeadShots\"",
    "\"AllDeadShots\"",
    "<NUM>",
    "<ID>",
    "<DIGIT>",
    "<CHAR>",
    "<DECIMAL>",
  };

}
